# Generated by Django 6.0.1 on 2026-01-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_customer_first_name_alter_customer_last_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
