# Generated by Django 6.0.1 on 2026-01-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_add_slug_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="zip",
            field=models.CharField(default="-", max_length=16),
        ),
    ]
